### PR TITLE
@alloy => Add support for RSVP guests

### PR DESCRIPTION
**Pull request by mzikherman**
- Also renames from `interactive` to `action`

I went with a join table, I'm thinking we may want to add some field later on around the guest's invite? If not, it should be pretty easy to kill `RsvpGuest` and roll with `has_and_belongs_to_many`

### CODE REVIEW

**Comment by mzikherman** [comment]
Not crazy about this modeling, but throwing something up for now...comments welcome!

**Comment by joeyAghion** [comment]
* It's odd that the primary attendee(s) (the ones invited to an event) are in a totally different table than other attendees. You'd need different queries (or a `UNION` 😬) to effectively list attendees.
* Similarly, data about their attendance (e.g., their review of the snacks) couldn't be straightforwardly associated with a single model.
* Seems like a guest wouldn't be easily associated with their own `Person` record in this system, but would instead be associated with the record of the invitee who brought them along.
* It also expects a 1-to-1 invitee-to-guest mapping, while in reality there might be multiple invitees (_Duke and Duchess Foo_) who bring along their guest (_Joe Plumber_).

Maybe we shouldn't organize this important data around the "act" of RSVP-ing, but instead around their status as an attendee? Then whether they'd been invited and RSVP-ed or attended as a guest of someone else could just be an attribute of their `Attendance`. Each could have associated data (e.g., review, comments) and even refer to their own `Person`.

**Comment by mzikherman** [comment]
> It's odd that the primary attendee(s) (the ones invited to an event) are in a totally different table than other attendees. You'd need different queries (or a UNION 😬) to effectively list attendees.

That doesn't necessarily seem like an issue to me. We are intentionally modeling them separately, the actual invitee (who RSVP'ed), and their guests. While all of them at the end of the day are attendees of some event, having two queries to get all the RSVP'ed guests and _their_ guests isn't going to be an issue. Plus, we don't even have any event information here, that's in its own system. A print out guest list for the event could easily be accommodated as well (emailed list, etc.)

> Similarly, data about their attendance (e.g., their review of the snacks) couldn't be straightforwardly associated with a single model.

Wouldn't that be what the `RsvpGuest` join is for? That represents all the rsvp's that a person was invited to as a guest, and so we could enrich that with other fields when needed.

> Seems like a guest wouldn't be easily associated with their own Person record in this system, but would instead be associated with the record of the invitee who brought them along.

That's what the join model does?

> It also expects a 1-to-1 invitee-to-guest mapping, while in reality there might be multiple invitees (Duke and Duchess Foo) who bring along their guest (Joe Plumber).

Great point, the case of having a single (as present), or multiple (in your example) original invitees isn't supported. In that case, continuing along the logic here so far, we'd be updating the `Interaction` model to relate to more than one `Person`. That sort of feels like it could actually be interesting and correct, I'm going to explore that a bit more.

**Comment by dblock** [comment]
I think i'm with Joey on guest of a guest, the only difference between the person invited and their guest is a "guest of" relationship.

**Comment by dblock** [comment]
For RSVP it will be important to record attendance, but it feels like we'll want a separate record that someone has attended when they check-in. 

Note that multiple people can invite the same person to an event.

**Comment by mzikherman** [comment]
I'm thinking about things a bit differently: for us, what's important isn't the attendees at an event necessarily, but people and our interactions with them.

A person visiting rsvp.artsy.net and entering their information (as well as guest information) is an interaction with us that explicitly is created `Rsvp` and `Interaction`. Then `RsvpGuest` is created for each guest.

So the same person can be invited by multiple people. If I rsvp on the site and invite Joey, and you do as well, that's just 2 rsvp's that he's a part of. That's totally supported and stored by this system.

Now what might be muddling this situation, is we also sort of have the question of 'did they actually attend the event? who actually attended the event?'. This is something I don't think the current RSVP app/system currently supports. I honestly hadn't really thought of it much. It just supports the act of RSVP'ing (and voluntarily listing some guests).

The specific questions of _who_ attended a certain event seems like something we should enable, but not the first-class responsibility of a CRM (IMO).

The act of recording the actual attendance (+ other info from the in-person interaction perhaps?), if that is indeed something we'd like to do, could be accomplished by adding fields to the join model? Such as `admin_notes`, `review`, `attended` (boolean), etc. In the case of being invited multiple times we can simply mark all of those with the same data- that way we know you attended and who you were the multiple people that invited you.

From the standpoint of looking at a UI with info for a given person (such as a simple admin CRM UI here), you could see who all the people you've ever invited to an event, all the rsvp's you did have, etc. And all the invites you've received from people.

**Comment by joeyAghion** [comment]
It's important that we create `Person` records for every attendee/invitee/collector/other our system learns about. That's where I was getting hung up, and I think I misunderstood and assumed the `RsvpGuest` referred to their inviter's `Person`. As long as there are 2 `Person`s when a single invitee brings along another guest, I think I'm :+1.


> > Similarly, data about their attendance (e.g., their review of the snacks) couldn't be straightforwardly associated with a single model.
> 
> Wouldn't that be what the RsvpGuest join is for?

By that^ I meant data _about_ their attendance. Since an attendance isn't modeled directly but is instead split over `Rsvp`s and `RsvpGuest`s, it would be awkward to model things like seat assignments, raffle ticket numbers, event evaluations... Is that more clear? This all might be out of scope for this system. I was just commenting about the modeling abstractly since that's what we have to go on at this point.

**Comment by mzikherman** [comment]
> It's important that we create Person records for every attendee/invitee/collector/other our system learns about. That's where I was getting hung up, and I think I misunderstood and assumed the RsvpGuest referred to their inviter's Person. As long as there are 2 Persons when a single invitee brings along another guest, I think I'm :+1.

Yup, we do that since `RsvpGuest` is the invitee. I actually played around with naming it `RsvpInvitee`, but that didn't come out as nice. I did explore rsvp's encompassing all attendees (and circumventing `Interaction` for a large part, it wasn't needed), but that just feels like re-building the _actual_ RSVP app, and not just syncing data + preparing for future iterations. In the current scheme we'd even be able to model interactions with a +1'ed guest, tying it to the RSVP much like with the rsvp'er.

I think some of the examples given (print out all attendees at an event, seat assignments, reviews, etc.) _are_ perhaps more awkward with this than with something like `Attendance` and `Event`, to me that seems a bit out of scope for a CRM. It's certainly possible in this setup, and so can/should easily be delegated to the rsvp app (or wherever).

I'm tempted to still cast my vote for this solution, but curious if there are objections.

**Comment by alloy** [comment]
Nope, none on my end. We definitely don’t want to rebuild the RSVP app here, so this looks good to me for now.

**Pull request merged**
